name : terraform file

on:
  push :
    branch :
        - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
  
      steps :
        - uses : actions/checkout@v4
      
      
      
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v4
        runs : 
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        working-directory: ./terraform-practice     


      
